{% set version = "1.3.1" %}
{% set sha256 = "d3293f2e03393281df7f88009f6cce27fe78a193b54efcbc36db5effcd6bdd8b" %}

package:
  name: rnablueprint
  version: {{ version }}

source:
   url: https://github.com/ViennaRNA/RNAblueprint/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - automake
    - autoconf
    - libtool
    - swig >=3.0.7
  host:
    - boost
    - python
    - perl
  run:
    - boost

test:
  commands:
    - echo '.' | RNAblueprint -n 1

about:
  home: https://github.com/ViennaRNA/RNAblueprint
  license: GPL3
  license_files: LICENSE
  summary: The RNAblueprint library solves the problem of uniformly sampling RNA/DNA sequences compatible to multiple structural constraints and sequence constraints.

extra:
  identifiers:
    -  doi:10.1093/bioinformatics/btx263
